# This is a TOML document containing xbuild setup information

title = "XBUILD setup"

[[icons]]
tag  = "conventions"
name = "cancelled"
icon = ":material-regular:`remove_shopping_cart;2em`"
desc = "Product never shipped or cancelled."
[[icons]]
tag  = "conventions"
name = "intransit"
icon = ":material-regular:`local_shipping;2em;`"
desc = "An item in transit."
[[icons]]
tag  = "conventions"
name = "present"
icon = ":material-regular:`verified;2em;sd-text-success`"
desc = "This item is present in the collection."
[[icons]]
tag  = "conventions"
name = "notpresent"
icon = ":material-regular:`thumb_down;2em;sd-text-danger`"
desc = "This item has not yet been acquired for the collection."
[[icons]]
tag  = "conventions"
name = "advanceinfo"
icon = ":material-regular:`lock_open;2em;sd-text-danger`"
desc = "Usually datasheets, this is preliminary or advance information and will be subject to change."
[[icons]]
tag  = "conventions"
name = "confirminfo"
icon = ":material-regular:`lock;2em;sd-text-success`"
desc = "This is published material relating to the product as sold."
[[icons]]
tag  = "conventions"
name = "2ndsource"
icon = ":octicon:`list-ordered;2em`"
desc = "A second-source item."
[[icons]]
tag  = "conventions"
name = "underoffer"
icon = ":material-regular:`gavel;2em;sd-text-danger`"
desc = "Under Offer."
[[icons]]
tag  = "media"
name = "magnetictape"
icon = ":material-regular:`voicemail;2em;`"
desc = "Magnetic Tape"
[[icons]]
tag  = "media"
name = "floppydisc"
icon = ":material-regular:`save;2em;`"
desc = "Floppy Disc"
[[icons]]
tag  = "media"
name = "punchedcard"
icon = ":material-regular:`margin;2em;`"
desc = "Punched Card"
[[icons]]
tag  = "media"
name = "datacartridge"
icon = ":material-regular:`storage;2em;`"
desc = "Data Cartridge"
[[icons]]
tag  = "conventions"
name = "document"
icon = ":material-regular:`document_scanner;2em;`"
desc = "Part of a larger single document."



