name: Deploy Static API to GitHub Pages

on:
  push:
    branches:
      - main  # Runs every time you push to the main branch

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-python-version: '3.x'

      - name: Generate JSON files from SQLite
        run: python xbuild_support/build_api.py

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4